name: qa-deployer
on:
  push:
    branches:
      - '*'
      - '!main'
      - '!master'
jobs:
  zip-n-deploy:

    permissions:
        contents: 'read'
        id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/172073939371/locations/global/workloadIdentityPools/qa-pool/providers/gh-provider'
          service_account: 'pinewood-qa@dionricky-personal.iam.gserviceaccount.com'

      - name: 'Install gcloud CLI'
        run: |
          sudo apt-get install apt-transport-https ca-certificates gnupg \
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg \
          sudo apt-get update && sudo apt-get install google-cloud-cli \

      - name: 'Set default gcloud project'
        run: gcloud config set project "dionricky-personal"