name: qa-deployer
on:
  push:
    branches:
      - '**'
      - '!main'
      - '!master'
jobs:
  build-n-deploy:
    
    permissions:
        contents: 'read'
        id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/172073939371/locations/global/workloadIdentityPools/qa-pool/providers/gh-provider'
          service_account: 'pinewood-qa@dionricky-personal.iam.gserviceaccount.com'

      - name: 'Build pinewood'
        run: |
          mkdir build && cp main.py ./build && cp requirements.txt ./build
          cd build && zip -r ../build.zip *; cd ..

      - name: 'Upload build to GCS'
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          DATE=$(date "+%Y-%m-%d")
          gcloud storage cp ./build.zip gs://dionricky-service/pinewood/build/${BRANCH}/build_${DATE}.zip

      - name: 'Deploy to Cloud Functions'
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          DATE=$(date "+%Y-%m-%d")
          gcloud functions deploy pinewood-main \
            --gen2 \
            --region='us-east1' \
            --runtime='python39' \
            --source="gs://dionricky-service/pinewood/build/${BRANCH}/build_${DATE}.zip" \
            --entry-point='main' \
            --trigger-topic='trigger_pinewood'